name: flutter_ruby_text
description: A Flutter package for displaying ruby text.
version: 0.0.1
homepage: https://henryypin.github.io/flutter_ruby_text
repository: https://github.com/henryypin/flutter_ruby_text
issue_tracker: https://github.com/henryypin/flutter_ruby_text/issues

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
